apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: collector-prometheus-service-monitor
  labels:
    app.kubernetes.io/component: opentelemetry-collector-prometheus
    app.kubernetes.io/instance: default.otel-collecto
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/name: otel-collector-collector
  endpoints:
  - port: promexporter